### ISSUE TITLE
Modification of the Fit Info display

### ISSUE THREAD

**Issue by a-monsch** [PhiLFitters/kafe2#105]
It is helpful if the fit Info can be adjusted individually for each fit object.
For three objects the detailed fit info would only be displayed for the desired function and for the others not or only the fit quality.

Would be easier if the existing argument `with_fit_info` in the `Plot.plot` method would accept both booleans and lists of booleans or list of strings/booleans combinations.

example with:
```
fit_objects = [fit_object_1, fit_object_2, fit_object_3]
plot_object = kafe2.Plot(fit_objects)
plot_object.plot(with_fit_info=<THIS>)
```

so far:
```
with_fit_info=True
with_fit_info=False
```
All fit infos are displayed or hidden.

possible extension 1:
`with_fit_info=[True, False, False]:`
The fit info is only displayed for the first fit object

possible extension 2:
`with_fit_info=[True, "quality", False]`
The fit info of the first object is created completely and only the fit quality of the second object. The fit info of the third object is not created.
(At this point True or "all" could also be set)

Possible modification:

In `Plot.plot()` before the loop over `_axes_plots`:

```
with_fit_info_ = [with_fit_info for _ in _axes_plots] if not isinstance(with_fit_info, list) else with_fit_info
with_fit_info_ = [with_fit_info_[item["fit_index"]] for item in _axes_plots]
```

And then modify the loop too:

```
for _i_plot, (_plot_dict, with_fit_info) in enumerate(zip(_axes_plots, with_fit_info_)):
    ....
```

For the difference between `"all"`/`True`,` "quality"`,` False`: `with_fit_info` must be passed to the `_get_fit_info` method.

There for the `FIT_INFO_STRING_FORMAT` possibly replace the `parameters` in `format` method with an empty string if passed `with_fit_info` is `"quality"` or pass the whole variant if `with_fit_info` is `True` or `"all"`.

Most likely there is an even smarter way to achieve the same thing... The fact remains that a modification of the fit parameters would be advantageous when several fit objects are present in a plot.

This proposal would not introduce an additional option, but would modify an existing one.

**Comment by dsavoiu** [comment]
This is interesting! I think we should consider some variant of this for the next major release.

The extension to a `list` instead of a single value should be fairly straightforward.

Allowing strings like `"quality"`, etc., in addition to booleans should also be fairly simple, but we should discuss what options make sense here.

Ultimately, to give users full control over what is displayed in the fit info, the semi-hard-coded approach using `FIT_INFO_STRING_FORMAT` would have to be revised. Perhaps it would make sense to allow passing a callable instead of `True`/`"quality"`/etc., which would then be called instead of the default `_get_fit_info` method.

**Comment by cverstege** [comment]
2e388b007d3b7c2aaad9b38c7c362077b9a63887 implements toggling the fit info for each fit independently.

Adding more options via strings is imo (after looking at the code) a bigger undertaking, as the `_get_fit_info()` is already fairly complicated.

This could be implemented when revisiting the corresponding code and trying to simplify it. But this is too much work to get it done in time for the 2.3 release.

I'm moving this request to 2.4. I hope the independent boolean toggling for fits is good enough for now.

**Comment by cverstege** [comment]
Plotting just data, without any model function is possible by passing a data container to the plot. Additionally the fit information can be toggled via the `fit_info` keyword in the `plot` function.
Example:
```
plot = Plot([fit_1,fit_2, aux_data])
plot.plot(fit_info=[True, False, True])
```

I think this is good enough.
