### ISSUE TITLE
XYContainer

### ISSUE THREAD

**Issue by ralfulrich** [PhiLFitters/kafe2#121]
First: kafe2 is great. Thanks for this project. I just started to look at it, and i found some things that are either strange, not yet well documented, or just missing. I will likely submit several dedicated Issues

**XYContainer can be constructed without uncertainties**

This violates the rule to only construct fully initialized objects, e.g.:
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-complete
In fact, XYContainter without uncertainties is useless in kafe2. No fit can run on data without uncertainties (unbinned fits need a different type of data to run on). 

**Why not add uncertainties to constructor and make it mandatory**

It is best if there is just exactly one way to do something in a library. This helps to avoid simple mistakes. Objects should always be created fully initialized. Uncertainties are at least as important as the data itself for the fit!

--> Side remark, in statistics there are only uncertainties not errors... maybe you need to create kafe3 by just running
  find ./ -type f -exec sed -i -e 's/error/uncertainty/g' {} \;
it is not very nice that in kafe2 you use "error" instead of "uncertainty"

**Comment by JohannesGaessler** [comment]
I understand your reasoning.
However, I do not think that making uncertainties mandatory in the constructor would be convenient for users.

When a user adds an uncertainty source to a container or fit by calling a method this creates another object inside the container that represents said uncertainty source.
This is to allow users to selectively enable/disable uncertainty sources.
To properly maintain this functionality I think constructors for container objects would need to either

1. accept a list of uncertainty objects created by the user or
2. accept a list of some data structure like a dict that represents one uncertainty source each.

I think both of these approaches would be inconvenient to use when compared to a method call.
