### ISSUE TITLE
Dev requirements and doc requirements

### ISSUE THREAD

**Issue by cverstege** [PhiLFitters/kafe2#157]
There are currently two requirements.txt for development.
One in the main directory named `dev_dependencies.txt` and one in the doc directory named `requirements.txt`.

We either have to separate them clearly, e.g. removing sphinx and mock from the dev_dependencies and move them to the doc requirements or merge them into one by adding sphinx_bootstrap_theme to the dev_dependencies and deleting the `requirements.txt` inside the doc directory.

**Comment by JohannesGaessler** [comment]
I think we should have just one file that lists dependencies.
I think we should add sphinx_bootstrap_theme to dev_dependencies.txt, delete doc/src/requirements.txt, and adjust developer_guide.rst so that it mentions sphinx_bootstrap_theme.

**Comment by cverstege** [comment]
Reopening as doc requirements is needed for the docs to build on readthedocs. We need to update the readthedocs settings in order to solve this.

**Comment by MitchiLaser** [comment]
This issue seems to be closed with the new release (2.8.1) as the rtd and dev dependencies have been fully integrated in the pyproject.toml file and the rtd config now relies on these settings.
