### ISSUE TITLE
CI & dependency improvements

### ISSUE THREAD

**Issue by AlexanderKaschta** [PhiLFitters/kafe2#211]
**Is your feature request related to a problem? Please describe.**
No, it's not problem related. I've just noticed this looking into this code repository.

**Describe the solution you'd like**
I've seen in the code base, that you're using `flake8` for linting. Would it make sense to add it to the `dev_dependencies.txt` file as it's used in developement? An additional idea would be to use GitHub Actions to run such code linting (or even other unit tests, coverage, ...) on each commit to ensure code quality.

**Describe alternatives you've considered**
The alternative would be doing nothing.

**Additional context**
An example CI pipeline used in PhyPiDAQ can be found under https://github.com/PhyPiDAQ/PhyPiDAQ/blob/main/.github/workflows/action_code_check.yml .

**Comment by cverstege** [comment]
AFAIK we don't use any linting as of now. This of course has to change when more people start working on this project.
I guess if we would do a test run on the existing code base, a lot of issues would occur.
Before implementing this as a GitHub action, we would first have to define the rules we want to stick to and maybe adapt the existing code base.

**Comment by cverstege** [comment]
A test run of flake8 with the config found in our repo had 2087 issues. So there is definitely some code cleanup to be done.

**Comment by AlexanderKaschta** [comment]
It surprises me to hear, that you don't use linting, because the config file `.flake8rc` (even thought it doesn't match the `flake8` standard) in the root folder seems to suggest it. It's still a nice feature request (which might happen in the future)

**Comment by cverstege** [comment]
Yes, there are plans to include it. I guess it's time to so now as kafe2 starts to get attention from people other than the developers.
I'll start a PR including code cleanups. Maybe we can merge it in time for the release for this summer semester.

**Comment by JohannesGaessler** [comment]
I am the person that added the .flake8rc file. The reason was that this file is being used by IDEs to determine whether the user should be shown a warning regarding whether the length of lines is acceptable (@dsavoiu and me agreed on 100 characters). Until now I have spent essentially no time on refactoring code for no other reason than to satisfy flake8 since the opportunity cost seemed too high.

**Comment by cverstege** [comment]
I'm thinking about reformatting the whole code base with a tool like [black](https://black.readthedocs.io/en/stable/index.html). This would define a style for future commits and avoid a lengthy discussion on which style to use. It could also be used as a pre-commit hook to automatically apply the code style.
This in turn would touch every file, which is not ideal. I'm thinking about performing one big commit, which then can be excluded when using git blame.
When formatting big arrays and matrices, the magic commands `# fmt: off` and `# fmt: on` would have to be used.

**Comment by cverstege** [comment]
See PR #213 for more information. PyTest has already been deployed with PR #212
