### ISSUE TITLE
Unreasonale warning  in histogram container

### ISSUE THREAD

**Issue by GuenterQuast** [PhiLFitters/kafe2#214]
**Describe the bug**
Histogram fits produce the warning:
/usr/local/lib/python3.10/dist-packages/kafe2/fit/histogram/container.py:128: UserWarning: Historam data is int. Make sure to consider this for your bin edges!

**To Reproduce**
happens in all histogram fits

This warning stems from a check on int for the bin counts. which is int !
Please remove, or test on input data !

**Comment by JohannesGaessler** [comment]
Fixed on dev via https://github.com/PhiLFitters/kafe2/commit/295788936005626e3147f590fb8c9c47f26c7378
