### ISSUE TITLE
hit_fit() in wrappers.py:  label "model density" cannot be changed (should be taken from model_name ?

### ISSUE THREAD

**Issue by GuenterQuast** [PhiLFitters/kafe2#217]
**Describe the bug**

**To Reproduce**
Ideally, include a link to the script and dataset you used when encountering the bug. You can paste your scripts for example to [Github Gist](https://gist.github.com) or [Pastebin](https://pastebin.com).
Additionally you can describe the steps to reproduce the behavior and give us a minimal example when this bug occurs.

**Expected behavior**

**Traceback**
Please attach the traceback found in the terminal when you encounter the bug. This can be uploaded to [Github Gist](https://gist.github.com) or [Pastebin](https://pastebin.com) as well. Don't forget to give us the link.

**System:**
 - OS: [e.g. Windows10 or Ubuntu 18.04]
 - Python Version: [eg. 2.7.17 or 3.8.1]

**Additional context**

**Comment by JohannesGaessler** [comment]
I added code that infers model error band label and model density labels from model labels. Do we need the ability to set custom model density labels?

**Comment by JohannesGaessler** [comment]
Fixed on dev via https://github.com/PhiLFitters/kafe2/commit/b1050aaa1691f7995eb75f23096c44b53fcf1042
