### ISSUE TITLE
Can't clone repository on Windows

### ISSUE THREAD

**Issue by AlexanderKaschta** [PhiLFitters/kafe2#229]
**Describe the bug**

`git clone https://github.com/PhiLFitters/kafe2.git` fails with the following error message

```
error: invalid path 'doc/kafe2_paper:_A_Modern_Tool_for_Model_Fitting_in_Physics_Lab_Courses.pdf'
fatal: unable to checkout working tree
```

**To Reproduce**
1. Get a Windows instance
2. Run `git clone https://github.com/PhiLFitters/kafe2.git`

**Expected behavior**
A successful git clone

**Traceback**
```
error: invalid path 'doc/kafe2_paper:_A_Modern_Tool_for_Model_Fitting_in_Physics_Lab_Courses.pdf'
fatal: unable to checkout working tree
```

**System:**
 - OS: Windows 10
- Git: 2.30.1

**Additional context**
It's not allowed to have a colon `:` in filenames on Windows, see https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#:~:text=Use%20any%20character%20in%20the,%3E%20(greater%20than) . I will create a merge request for this.

**Comment by cverstege** [comment]
:facepalm: Just windows things
Thanks for noticing this.

**Comment by AlexanderKaschta** [comment]
I've replaced the colon with an underscore. The merge request #230 is ready for review.

**Comment by cverstege** [comment]
It will be merged into master with the next release
