### ISSUE TITLE
plot.customize() needs iterable value(s)

### ISSUE THREAD

**Issue by cverstege** [PhiLFitters/kafe2#63]
The `plot.customize()` function needs iterable values.
For example the call `plot.customize('data', 'markersize', 3)` will fail with:
```
  File "/home/cedric/.local/lib/python3.7/site-packages/kafe2/fit/_base/plot.py", line 1071, in customize
    for _val in values:
TypeError: 'int' object is not iterable
```

As a workaround `plot.customize('data', 'markersize', [3])` can be used.

**Comment by dsavoiu** [comment]
Not really a bug, as the documentation explicitly asks for
an iterable (and an iterable would be necessary when there
are multiple fit objects anyway).

I agree the call could be made more user-friendly, for instance
if non-iterables like `3` were cast to iterables of the correct length
(i.e. `[3] * num_fits`) automatically, but the canonical API call should still
take an iterable.

```
def customize(self, plot_type, keyword, values):
    """Set values for keyword arguments used for plots with type `plot_type`.
    ...
    :param values: values that the keyword argument should take for each fit. Can be a list of values
        with a length corresponding to the number of `fit` objects managed by this `Plot` instance,
        or a list of tuples of the form ``(index, value)``
    :type values: list of values or list of 2-tuples like ``(index, value)``
```

**Comment by JohannesGaessler** [comment]
Fixed via https://github.com/PhiLFitters/kafe2/commit/63e6f2192d04b73fbadce2f7dbd2fc7f4b87d04a
