### ISSUE TITLE
Remove code duplicates

### ISSUE THREAD

**Issue by cverstege** [PhiLFitters/kafe2#99]
The current kafe2 code contains a lot of duplicates: https://www.codefactor.io/repository/github/dsavoiu/kafe2/issues?category=Duplication
In general, if a docstring is identical to the base class/function docstring, it can be removed and the default docstring from the base class will be used with most IDEs and hopefully Sphinx (need to check that).
Also lots of functionality is shared between classes. In this case it can be helpful to move some of the code into the base class and use a super function call in combination with additional processing.

I think that the kafe2 codebase can be reduced by a lot of lines of code while improving readability and maintainability.

**Comment by JohannesGaessler** [comment]
This issue is too general.
